apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /space-game
        pathType: Prefix
        backend:
          service:
            name: space-game-service
            port:
              number: 80
